name: file_manager_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  base64: ^1.0.0
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  disk_space: ^0.2.1
  file_manager: ^1.0.2
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  grpc: ^3.0.0
  protobuf: ^2.0.0
  flutter_secure_storage: ^9.0.0
  get: ^4.6.5
  http: ^1.2.1
  path_provider: ^2.0.14
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  sizer: ^2.0.15
  storage_info: ^0.0.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/3d/
  # Fonts and other assets can be declared here as needed.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # See https://flutter.dev/custom-fonts/#from-packages for more details.
